Remove arbitrary redirect port from connector.
pegasystems/docker-pega-web-ready pull request #183
Opened 2023-02-03 21:08 UTC by misterdorito

This fixes #104

2023-02-03 21:16 UTC, APegaDavis approved these changes

2023-02-03 22:07 UTC, APegaDavis requested changes
redirectPort has the following description in Tomcat's doc:
>If this Connector is supporting non-SSL requests, and a request is received for which a matching <security-constraint> requires SSL transport, Catalina will automatically redirect the request to the port number specified here.

The shipped web.xml has a few such security constraints. Is it possible for a client to have misconfigured their ingress to point to 8080, in which case we would break their redirect for these servlets by removing this redirect?

2023-02-06 16:02 UTC, APegaDavis approved these changes

2023-02-06 16:11 UTC, Heshma approved these changes

2023-02-06 16:29 UTC, khick77 approved these changes

2023-02-06 16:39 UTC, merged