Bugfix/bug 798106
pegasystems/docker-pega-web-ready pull request #196
Opened 2023-09-05 15:10 UTC by baylp2022

BUG-798106 - Unable to set speculative exec policy props and custom retry count in pega-helm-chart

2023-09-06 12:31 UTC, kingakowalska1 requested changes
Hi,

My only comment is that there should be periods at the end of the sentences in the Purpose column.

For example:

Is:
Specify the number of retries attempted when CASSANDRA_CUSTOM_RETRY_POLICY is true

Should be:
Specify the number of retries attempted when CASSANDRA_CUSTOM_RETRY_POLICY is true.

Thanks!
Kinga

2023-09-06 12:38 UTC, taz-pega-work reviewed
Can we tighten up the language and add default valuies if there are any?

2023-09-06 15:31 UTC, baylp2022 commented on README.md
> +CASSANDRA_CUSTOM_RETRY_POLICY_COUNT | Specify the number of retries attempted when CASSANDRA_CUSTOM_RETRY_POLICY is true |
Thank you. I made the recommended changes.

2023-09-06 15:49 UTC, taz-pega-work reviewed
looks good. thanks for collaborating!

2023-09-06 18:42 UTC, taz-pega-work approved these changes
excellent updates here. Thanks for your collaboration @baylp2022 . These read well now.

2023-09-07 09:02 UTC, kingakowalska1 approved these changes
Looks great, thanks!

2023-09-07 17:14 UTC, taz-pega-work commented
with the reviewers complete, this looks ready to mearge

2023-09-07 17:14 UTC, merged